" {{{ HISTORY
    set history=500

    if has("autocmd")
      au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
    endif
" }}}

" {{{ PLUGINS
    " {{{ GOOGLE
		set nocompatible
		source /usr/share/vim/google/google.vim
		filetype plugin indent on
		syntax on
    " }}}

		" {{{ VUNDLE
"		set nocompatible              " be iMproved, required
"		filetype off                  " required
"
"		" set the runtime path to include Vundle and initialize
"		set rtp+=~/.vim/bundle/Vundle.vim
"		call vundle#begin()
"		" alternatively, pass a path where Vundle should install plugins
"		"call vundle#begin('~/some/path/here')
"
"		" let Vundle manage Vundle, required
"		Plugin 'VundleVim/Vundle.vim'
"
"		" The following are examples of different formats supported.
"		" Keep Plugin commands between vundle#begin/end.
"		" plugin on GitHub repo
"		Plugin 'tpope/vim-fugitive'
"		" plugin from http://vim-scripts.org/vim/scripts.html
"		" Plugin 'L9'
"		" Git plugin not hosted on GitHub
"		Plugin 'git://git.wincent.com/command-t.git'
"		" git repos on your local machine (i.e. when working on your own plugin)
"		Plugin 'file:///home/gmarik/path/to/plugin'
"		" The sparkup vim script is in a subdirectory of this repo called vim.
"		" Pass the path to set the runtimepath properly.
"		Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
"		" Install L9 and avoid a Naming conflict if you've already installed a
"		" different version somewhere else.
"		" Plugin 'ascenator/L9', {'name': 'newL9'}
"
"		" All of your Plugins must be added before the following line
"		call vundle#end()            " required
"		filetype plugin indent on    " required
"		" To ignore plugin indent changes, instead use:
"		"filetype plugin on
"		"
"		" Brief help
"		" :PluginList       - lists configured plugins
"		" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
"		" :PluginSearch foo - searches for foo; append `!` to refresh local cache
"		" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"		"
"		" see :h vundle for more details or wiki for FAQ
"		" Put your non-Plugin stuff after this line
"    " }}}

    " {{{ PLUG
    call plug#begin('~/.vim/plugged')
    Plug 'morhetz/gruvbox'
    Plug 'edkolev/tmuxline.vim'
    Plug 'vim-airline/vim-airline'
    call plug#end()
    " }}}

    filetype plugin on
    filetype indent on

    set autoread
" }}}

" {{{ MOVEMENT
    " Vertical jump with 'j' and 'k'
    set so=7
" }}}

" {{{ BACKSPACE
    set backspace=eol,start,indent
" }}}

" {{{ SEARCH
    set ignorecase
    set smartcase
    set hlsearch
    set incsearch
" }}}

" {{{ REGEX
    set magic
" }}}

" {{{ BRACKETS
    set showmatch
    set mat=2
" }}}

" {{{ SYNTAX HIGHLIGHTING
    syntax enable
" }}}

" {{{ STATUSLINE
    " always show Powerline/Airline
    set laststatus=2

    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#left_sep = ' '
    let g:airline#extensions#tabline#left_alt_sep = '|'
    let g:airline#extensions#tabline#right_sep = ' '
    let g:airline#extensions#tabline#right_alt_sep = '|'
    let g:tmuxline_powerline_separators = 0

    let g:airline#extensions#virtualenv#enabled = 1

    " Always show current position
    set ruler
" }}}

" {{{ COLORING
    colorscheme gruvbox
    set background=dark
    " for TMUX
    set t_Co=256
    set colorcolumn=80
" }}}

" {{{ FORMATTING
    set encoding=utf8
" }}}

" {{{ FOLDING
    set fdm=marker
" }}}

" {{{ TABBING & INDENTS
    set expandtab
    set smarttab
    set shiftwidth=2
    set tabstop=2
    set lbr
    set textwidth=80
    set ai
    set si
    set wrap
    set cinoptions=l1
" }}}

" {{{ WINDOWS
    set splitright
" }}}

" {{{ LINE NUMBERS
function! NumberToggle()
  if(&relativenumber == 1)
    set nu
    set rnu!
  else
    set rnu
    set nu!
  endif
endfunc

nnoremap <C-N><C-N> :call NumberToggle()<CR>
"nnoremap <C-N><C-N> :set rnu!<CR>:set nu!<CR>
" Set Line Numbers to initially on
set nu
" }}}

" {{{ MAPPINGS
    " map control-backspace to delete the previous word
    imap <C-BS> <C-W>
    map <ESC>[1;5D <C-Left>
    map <ESC>[1;5C <C-Right>
" }}}
