#! /bin/sh

[ $# -ne 1 ] && exit 1

status_fifo=$1

{ while read -r line ; do 
    msg=${line#?}
    urg="low"
    case $line in
        H*)
            # Keys pressed
            duration=500
            ;;
        C*)
            # Command executed
            duration=1000
            ;;
        B*)
            # Begin Chain (chord)
            duration=2000
            urg="critical"
            ;;
        E*)
            # End Chain (chord)
            duration=500
            ;;
        *)
            # Unknown examples
            duration=5000
            msg="Unknown character ${line:0:1} in line $line"
            urg="critical"
            ;;
    esac
    notify-send -u $urg -t $duration "$msg"
done } < "$status_fifo"
